# Generated by Django 5.0.2 on 2024-12-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phishing_URL', models.CharField(max_length=300)),
                ('type', models.IntegerField()),
            ],
        ),
    ]
