# Generated by Django 5.0.2 on 2024-12-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishing',
            name='phishing_URL',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
